import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Provider from "./Provider";
import Protected from "./Protected";

export const metadata: Metadata = {
  title: "ASFWA - 4H LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Provider>
          <Protected>
            <div className="flex md:h-screen bg-gray-50">
              {/* Sidebar - Hidden on mobile, shown on desktop */}
              <Sidebar />

              {/* Main Content Area */}
              <div className="flex-1 flex flex-col overflow-hidden lg:ml-0">
                <Header />
                <main
                  className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8"
                  style={{ background: "var(--bgGradient)" }}
                >
                  {children}
                </main>
              </div>
            </div>
          </Protected>
        </Provider>
      </body>
    </html>
  );
}
